# Q-Table Learning

In [8]:
import gym
import numpy as np

### Load the environment

In [9]:
env = gym.make('FrozenLake-v0')

### Implement Q-Table learning algorithm

In [33]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = 1
num_episodes = 5000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [34]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.0034


In [35]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.29772421e-02   3.62781611e-02   2.05240886e-03   1.57420880e-01]
 [  2.56040572e-03   3.60059480e-03   0.00000000e+00   1.57420880e-01]
 [  6.29061601e-03   6.15769037e-03   3.41808671e-03   1.57420880e-01]
 [  0.00000000e+00   4.25094992e-03   1.51752836e-03   1.57420880e-01]
 [  3.46778235e-02   4.69998113e-05   1.43920022e-03   3.50128733e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.56938338e-03   0.00000000e+00   0.00000000e+00   1.53403307e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.77191594e-03   1.02065812e-03   2.68648229e-04   1.05761973e-02]
 [  0.00000000e+00   0.00000000e+00   1.28165546e-03   1.05389880e-02]
 [  0.00000000e+00   0.00000000e+00   7.76288263e-01   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1